### ISSUE TITLE
TypeError: Cannot read property 'toastClass' of undefined

### ISSUE THREAD

**Issue by shotap** [Foxandxss/angular-toastr#107]
Hi, I added the toastr to my project and i used the next settings:

```javascript
  .config(function(toastrConfig) {
      angular.extend(toastrConfig, {
          closeButton: true,
          closeHtml: '<button>&times;</button>',
          positionClass: 'toast-bottom-full-width',
          progressBar: true,
          timeOut: 3000
      });
  })
```
and inserted the directive as `<toast></toast>`

and I'm getting the next error:
```
TypeError: Cannot read property 'toastClass' of undefined
    at toastLinkFunction (http://localhost:9001/bower_components/angular-toastr/dist/angular-toastr.tpls.js:400:39)
    at invokeLinkFn (http://localhost:9001/bower_components/angular/angular.js:8219:9)
    at nodeLinkFn (http://localhost:9001/bower_components/angular/angular.js:7729:11)
    at http://localhost:9001/bower_components/angular/angular.js:7959:13
    at processQueue (http://localhost:9001/bower_components/angular/angular.js:13189:27)
    at http://localhost:9001/bower_components/angular/angular.js:13205:27
    at Scope.$eval (http://localhost:9001/bower_components/angular/angular.js:14401:28)
    at Scope.$digest (http://localhost:9001/bower_components/angular/angular.js:14217:31)
    at Scope.$apply (http://localhost:9001/bower_components/angular/angular.js:14506:24)
    at bootstrapApply (http://localhost:9001/bower_components/angular/angular.js:1448:15) <div class="{{toastClass}} {{toastType}}" ng-click="tapToast()">
```

Thank you in advance!

**Comment by Foxandxss** [comment]
You can't use toastr like that. You need to inject `toastr` somewhere and call its methods.

**Comment by shotap** [comment]
I injected it like any other dependency `angular.module('app', ['toastr'])`.   
Then I added the config and I have a service that calls its methods.

**Comment by Foxandxss** [comment]
And? It is working now?

**Comment by shotap** [comment]
Its working but I still get the error.

**Comment by Foxandxss** [comment]
Remove the `<toast></toast>` that is not doing anything.

**Comment by shotap** [comment]
Thanks.
